export const things: [thing: string, isPlural: boolean][] = [
    ['antifas', true],
    ['windmill cancer', false],
    ['homosexuals', true],
    ['the transgenders', true],
    ['universal healthcare', false],
    ['socialism', false],
    ['george soros', false],
    ['anarchists', true],
    ['commies', true],
    ['bisexuals', true],
    ['netflix', false],
    ['nancy pelosi', false],
    ['muslims', true],
    ['illegal aliens', true],
    ['black lives matter', false],
    ['taco trucks', true],
    ['joe biden', false],
    ['legalized marijuana', false],
    ['the clintons', true],
    ['obama', false],
    ['organic produce', false],
    ['radical liberals', true],
];

export const actions = [
    'abort',
    'eradicate',
    'control',
    'wreck',
    'abolish',
    'kill',
    'vaccinate',
    'loot',
    'burn down',
    'sexualize',
    'cheat',
    'erase',
    'force sex changes on',
    'take away',
    'cancel',
    'end',
    'overturn',
    'desecrate',
    'gut',
    'terrorize',
    'destroy',
    'ban',
    'overthrow',
    'censor',
    'repeal',
];

export const targets = [
    'the children',
    'babies',
    'the coal industry',
    'chick-fil-a',
    'abstinence-only education',
    'the american dream',
    'stay-at-home moms',
    'your guns',
    'traditional masculinity',
    'the suburbs',
    'your freedoms',
    'pick-up trucks',
    'our savior donald j. trump',
    'fossil fuels',
    'hobby lobby',
    'nascar',
    'your 401k',
    'traditional values',
    'fox news',
    'your religion',
    'small business',
    'private property',
];
