// NOTE: these may have to be all caps since we can't easily distinguish between names and objects
export const things = [
    'antifas',
    'witches',
    'windmill cancer',
    'homosexuals',
    'the transgenders',
    'universal healthcare',
    'socialism',
    'george soros',
    'anarchists',
    'commies',
    'left-wing facists',
    'bisexuals',
    'netflix',
    'nancy pelosi',
    'legalized marijuana',
    'muslims',
    'illegal aliens',
    'black lives matter',
    'taco trucks',
    'puerto rico',
    'the clintons',
    'obama',
    'globalization',
    'ben & jerry\'s',
    'organic produce',
];

export const actions = [
    'marry',
    'devour',
    'abort',
    'eat',
    'eradicate',
    'control',
    'wreck',
    'abolish',
    'kill',
    'vaccinate',
    'loot',
    'burn down',
    'sexualize',
    'cheat',
    'erase',
    'force sex changes on',
    'take away',
    'cancel',
    'end',
    'desecrate',
    'overturn',
    'gut',
    'terrorize',
    'destroy',
    'ban',
    'overthrow',
    'censor',
    'touch',
    'repeal',
];

export const targets = [
    'the children',
    'babies',
    'the coal industry',
    'chick-fil-a',
    'christopher columbus',
    'abstinence-only education',
    'the american dream',
    'stay-at-home moms',
    'your guns',
    'traditional masculinity',
    'the suburbs',
    'my freedoms',
    'pick-up trucks',
    'fox news',
    'our savior donald j. trump',
    'fossil fuels',
    'hobby lobby',
    'nascar',
    'your 401k',
    'traditional values',
    'my religion',
    'your private thoughts',
    'small business',
    'private property',
];
